# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-05 18:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movie_avg_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='avg_rating',
            field=models.FloatField(default=0),
        ),
    ]
