# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-05 00:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_auto_20160505_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='movie_id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
