# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-05 00:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_auto_20160505_0024'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='movies',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='movies.Movies'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rating',
            name='rater',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='movies.Rater'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rating',
            name='movie_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='rating',
            name='user_id',
            field=models.CharField(max_length=255),
        ),
    ]
