# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-05 00:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_auto_20160505_0029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='movies',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='rater',
        ),
    ]
